import "/public/css/bootstrap.css"
import "/public/css/animate.min.css"
import "/public/css/odometer.min.css"
import "/public/css/swiper-bundle.min.css"
import "/public/css/styles.css"
import { Archivo } from 'next/font/google'
import { Provider } from "@/components/ui/provider"

const archivo = Archivo({
    weight: ['300', '400', '500', '600', '700', '800', '900'],
    subsets: ['latin'],
    variable: "--font-main",
    display: 'swap',
})

export const metadata = {
    title: 'Healingy - Therapy & Counseling Psychologist Next.js Template',
    description: 'Generated by create next app',
}

function ClientLayout({ children }) {
    return (
        <Provider>
            {children}
        </Provider>
    )
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${archivo.variable}`}>
                <ClientLayout>
                    {children}
                </ClientLayout>
            </body>
        </html>
    )
}


